# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkSaver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_link', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Saver',
        ),
    ]
