# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0002_auto_20170813_1422'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LinkSaver',
            new_name='Saver',
        ),
    ]
